trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python 3.8'
  
  - script: python "pythonversion1.py"
    displayName: 'Run pythonversion1.py'

  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: |
        print('This is Section 1 Azure Demonstration')
        print('KL-CSE')
    displayName: 'Run Inline Python Script'
