trigger:

- master


pool:


  vmImage: 'ubuntu-latest'


strategy:


  matrix:


    Python27:


      python.version: '3.8'



steps:


- task: UsePythonVersion@0


  inputs:


    versionSpec: '$(python.version)'


  displayName: 'Use Python $(python.version)'


- script: python "pythonversion1.py"



- task: PythonScript@0


  inputs:


    scriptSource: 'inline'


    script: |
      print('This is Section 1 Azure Demonstration')
      print('KL-CSE')